export const SCENE_LOGIN = 'LOGIN'
export const SCENE_INDEX = 'INDEX'
export const SCENE_SEARCH = "SEARCH"
export const SCENE_BOOK_INFO = "BOOK_INFO"
export const SCENE_BOOK_COLLECT = "BOOK_COLLECT"
export const SCENE_BOOK_COLLECT_ADD = "BOOK_COLLECT_ADD"